name: Manutenção do Bot de Contas

on:
  schedule:
    # Roda a cada 2 dias às 12:00 UTC (09:00 Horário de Brasília)
    - cron: '0 12 */2 * *'
  workflow_dispatch: # Permite que você rode manualmente clicando no botão

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependências
        run: pip install twilio

      - name: Executar Bot
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
        run: python bot.py